import Image from "next/image";
import Link from "next/link";
import SiteHeader from "./components/SiteHeader";
import SiteFooter from "./components/SiteFooter";
import ArrowIcon from "./components/ArrowIcon";
import { services, whatsappLink } from "./data";
import { fallbackNews, formatNewsDate, loadNews } from "./news-data";
import { cases, plans, testimonials } from "./business-data";

export const revalidate = 1800;

const steps = [["01", "Descoberta", "Entendemos o cenário, os objetivos e as prioridades do seu negócio."], ["02", "Estratégia", "Desenhamos a solução, o escopo e um caminho claro para a entrega."], ["03", "Desenvolvimento", "Construímos com acompanhamento próximo, qualidade e transparência."], ["04", "Evolução", "Publicamos, acompanhamos resultados e preparamos os próximos passos."]];

export default async function Home() {
  const latestNews = await loadNews(4);
  const timelineNews = latestNews.length ? latestNews : fallbackNews;
  return <main className="site-shell"><SiteHeader />
    <section className="hero hero-evolved"><Image className="hero-art" src="/technology-landscape.webp" alt="" fill priority sizes="100vw" /><div className="hero-orb orb-one" /><div className="container hero-grid"><div className="hero-copy reveal"><p className="eyebrow"><span /> Tecnologia, estratégia e desenvolvimento</p><h1>Transformamos desafios em <em>soluções digitais.</em></h1><p className="hero-lead">Criamos sites, sistemas, automações e experiências inteligentes para tornar sua empresa mais eficiente, conectada e preparada para crescer.</p><div className="hero-actions"><Link href="/contato" className="button">Encontrar minha solução <ArrowIcon diagonal /></Link><Link href="/servicos" className="text-link">Explorar soluções <ArrowIcon /></Link></div><div className="trust-row"><div><strong>Estratégia</strong><span>antes do código</span></div><div><strong>Sob medida</strong><span>para sua operação</span></div><div><strong>Evolução</strong><span>para crescer junto</span></div></div></div>
    <div className="solution-stage reveal delay-one"><div className="float-pill pill-top"><span>✓</span> Atendimento inteligente</div><div className="solution-card glass-card"><div className="card-top"><div><span className="mini-label">LESystems / Ecossistema</span><h2>Da ideia à evolução.</h2></div><span className="live-dot">● online</span></div><div className="solution-map"><div className="map-core"><span className="core-shine" aria-hidden="true" /><strong>LE</strong><small>estratégia digital</small></div>{services.map((service, index) => <Link key={service.slug} href={`/servicos/${service.slug}`} className={`map-node node-${index + 1}`}><span>{service.number}</span><b>{service.title.split(" ")[0]}</b></Link>)}</div><div className="card-footer"><span><i /> Soluções conectadas ao seu negócio</span><span>2026</span></div></div><div className="float-pill pill-bottom"><strong>IA + pessoas</strong><span>suporte para decidir melhor</span></div></div></div>
    <div className="container client-strip"><span>Tecnologia útil para</span><p>NEGÓCIOS LOCAIS</p><i /><p>EMPRESAS EM CRESCIMENTO</p><i /><p>PROFISSIONAIS</p></div></section>
    <section className="news-home" aria-labelledby="news-home-title"><div className="container"><div className="news-home-heading"><div><p className="eyebrow"><span /> Radar de tecnologia</p><h2 id="news-home-title">Notícias mundiais,<br /><em>em uma linha do tempo.</em></h2><p>Acompanhe os movimentos mais recentes em inteligência artificial, sistemas, inovação e segurança digital.</p></div><Link href="/noticias" className="button">Ver todas as notícias <ArrowIcon /></Link></div><div className="news-timeline">{timelineNews.map((item, index) => <a href={item.link} target="_blank" rel="noreferrer" className={index === 0 ? "is-latest" : ""} key={`${item.link}-${index}`}><span className="timeline-dot" aria-hidden="true" /><div className="timeline-meta"><span>{index === 0 ? "Mais recente" : item.category}</span><time>{formatNewsDate(item.date)}</time></div><h3>{item.title}</h3><p>{item.source}</p><b>Ler matéria <ArrowIcon diagonal /></b></a>)}</div></div></section>
    <section className="section services-section"><div className="container"><div className="section-heading"><div><p className="eyebrow"><span /> O que fazemos</p><h2>Cada necessidade ganha<br /><em>um caminho completo.</em></h2></div><p>Conheça cada solução em detalhes, entenda o que está incluído e inicie uma conversa já com o contexto certo.</p></div><div className="services-grid">{services.map((service) => <article className="service-card" key={service.slug}><div className="service-number">{service.number}</div><h3>{service.title}</h3><p>{service.short}</p><div className="tag-row">{service.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><Link href={`/servicos/${service.slug}`}>Ver todos os detalhes <ArrowIcon /></Link></article>)}</div><div className="section-action"><Link href="/servicos" className="button">Ver central de soluções <ArrowIcon /></Link></div></div></section>
    <section className="section showcase-section"><div className="container"><div className="section-heading"><div><p className="eyebrow"><span/> Aplicações práticas</p><h2>Projetos pensados para <em>resultados reais.</em></h2></div><p>Exemplos de como transformamos necessidades em soluções claras, úteis e preparadas para evoluir.</p></div><div className="showcase-grid">{cases.map(item=><article key={item.number}><span>{item.number} / {item.category}</span><h3>{item.title}</h3><p>{item.result}</p><Link href="/portfolio">Conhecer o caso <ArrowIcon/></Link></article>)}</div></div></section>
    <section className="section plans-section"><div className="container"><div className="section-heading"><div><p className="eyebrow"><span/> Formas de começar</p><h2>Um formato adequado ao <em>momento da empresa.</em></h2></div><p>As faixas são definidas após o diagnóstico, evitando pacotes genéricos ou promessas sem contexto.</p></div><div className="plans-grid">{plans.map(plan=><article className={plan.featured?"featured":""} key={plan.name}><span>{plan.featured?"Mais completo":"Formato"}</span><h3>{plan.name}</h3><p>{plan.description}</p><ul>{plan.items.map(item=><li key={item}>✓ {item}</li>)}</ul><small>{plan.note}</small><Link className="inline-action" href="/orcamento">Solicitar avaliação <ArrowIcon diagonal/></Link></article>)}</div></div></section>
    <section className="section testimonials-section"><div className="container"><p className="eyebrow"><span/> Experiência LESystems</p><div className="testimonial-grid">{testimonials.map(item=><blockquote key={item.name}><p>“{item.quote}”</p><footer><strong>{item.name}</strong><small>{item.role}</small></footer></blockquote>)}</div><div className="center-action"><Link className="button" href="/agendamento">Agendar uma conversa <ArrowIcon diagonal/></Link></div></div></section>
    <section className="section intelligence-section"><div className="container intelligence-grid"><div><p className="eyebrow"><span /> Orientação inteligente</p><h2>Dúvidas respondidas.<br /><em>Decisões mais simples.</em></h2><p>O assistente LESystems ajuda a entender serviços, organizar necessidades e encontrar o próximo passo. Quando necessário, encaminha a conversa para a equipe.</p><Link href="/suporte" className="button">Conhecer o suporte inteligente <span>✦</span></Link></div><div className="ai-visual"><div className="orbit orbit-a" /><div className="orbit orbit-b" /><div className="ai-core"><span>✦</span><strong>Assistente</strong><small>conhecimento LESystems</small></div><div className="ai-chip chip-one">Respostas imediatas</div><div className="ai-chip chip-two">Encaminhamento humano</div><div className="ai-chip chip-three">24h online</div></div></div></section>
    <section className="section process-section light-process"><div className="container process-grid"><div className="process-intro"><p className="eyebrow"><span /> Nosso processo</p><h2>Simples de entender.<br /><em>Sólido para entregar.</em></h2><p>Você acompanha cada etapa e sabe exatamente onde o projeto está. Comunicação clara, decisões conscientes e foco no que gera valor.</p><Link href="/contato" className="button">Planejar meu projeto <ArrowIcon diagonal /></Link></div><div className="steps">{steps.map(([number, title, text]) => <article key={number}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
    <section className="section about-section"><div className="container about-grid"><div className="about-visual"><div className="code-window"><div className="window-head"><span /><span /><span /><small>lesystems / projeto</small></div><pre><code><b>const</b> solução = {'{'}{"\n  "}<span>estratégia</span>: true,{"\n  "}<span>tecnologia</span>: &quot;moderna&quot;,{"\n  "}<span>suporte</span>: &quot;humano + IA&quot;{"\n"}{'}'};</code></pre><div className="window-result"><span>✓</span><p><strong>Pronto para evoluir</strong><small>Solução validada com o negócio</small></p></div></div></div><div className="about-copy"><p className="eyebrow"><span /> Sobre a LESystems</p><h2>Engenharia de software com <em>propósito.</em></h2><p>Aproximamos empresas da tecnologia de forma simples, estratégica e humana. Transformamos necessidades reais em produtos digitais eficientes e preparados para o futuro.</p><div className="values"><div><span>01</span><p><strong>Clareza em cada etapa</strong><small>Sem complicação ou linguagem desnecessária.</small></p></div><div><span>02</span><p><strong>Qualidade com intenção</strong><small>Cada escolha serve ao objetivo do projeto.</small></p></div><div><span>03</span><p><strong>Parceria de verdade</strong><small>Suporte próximo para construir a solução certa.</small></p></div></div></div></div></section>
    <section className="section quick-actions"><div className="container"><div className="section-heading compact"><div><p className="eyebrow"><span /> Próximo passo</p><h2>Escolha como prefere <em>começar.</em></h2></div></div><div className="action-grid"><Link href="/contato"><span>01</span><h3>Solicitar uma avaliação</h3><p>Envie sua necessidade e receba um contato da equipe.</p><b>Preencher cadastro <ArrowIcon /></b></Link><Link href="/suporte"><span>02</span><h3>Preciso de suporte</h3><p>Organize uma dúvida ou solicitação de projeto.</p><b>Abrir suporte <ArrowIcon /></b></Link><a href={whatsappLink("Olá, conheci o novo site da LESystems e gostaria de conversar sobre um projeto.")} target="_blank" rel="noreferrer"><span>03</span><h3>Conversar agora</h3><p>Abra o WhatsApp com a mensagem já preparada.</p><b>Iniciar conversa <ArrowIcon /></b></a></div></div></section><SiteFooter />
  </main>;
}
