import Image from "next/image";
import Link from "next/link";
import SiteHeader from "./components/SiteHeader";
import SiteFooter from "./components/SiteFooter";
import ArrowIcon from "./components/ArrowIcon";
import { services, whatsappLink } from "./data";
import { fallbackNews, formatNewsDate, loadNews } from "./news-data";

export const revalidate = 1800;

const socialPosts = [
  { image: "/social/post-01-conheca-lesystems.png", title: "Soluções digitais para o seu negócio", text: "Sites, sistemas, automações, inteligência artificial, integrações e suporte pensados para gerar resultados." },
  { image: "/social/post-02-importancia-engenharia.png", title: "Engenharia que fortalece empresas", text: "Planejamento técnico reduz falhas, amplia a segurança e prepara a operação para crescer." },
  { image: "/social/post-03-alem-do-codigo.png", title: "Muito além do código", text: "Descoberta, estratégia, desenvolvimento, testes, implantação e evolução formam uma solução sólida." },
  { image: "/social/post-04-seguranca-digital.png", title: "Segurança começa com boas práticas", text: "Ações simples ajudam a proteger dados, pessoas e a continuidade da empresa." },
];

export default async function Home() {
  const latestNews = await loadNews(3);
  const timelineNews = latestNews.length ? latestNews.slice(0, 3) : fallbackNews.slice(0, 3);

  return <main className="site-shell compact-home"><SiteHeader />
    <section className="hero hero-evolved"><Image className="hero-art" src="/technology-landscape.webp" alt="" fill priority sizes="100vw" /><div className="hero-orb orb-one" /><div className="container hero-grid"><div className="hero-copy reveal"><p className="eyebrow"><span /> Tecnologia, estratégia e desenvolvimento</p><h1>Transformamos desafios em <em>soluções digitais.</em></h1><p className="hero-lead">Criamos sites, sistemas, automações e experiências inteligentes para tornar sua empresa mais eficiente, conectada e preparada para crescer.</p><div className="hero-actions"><Link href="/contato" className="button">Encontrar minha solução <ArrowIcon diagonal /></Link><Link href="/servicos" className="text-link">Explorar soluções <ArrowIcon /></Link></div><div className="trust-row"><div><strong>Estratégia</strong><span>antes do código</span></div><div><strong>Sob medida</strong><span>para sua operação</span></div><div><strong>Evolução</strong><span>para crescer junto</span></div></div></div>
      <div className="solution-stage reveal delay-one"><div className="float-pill pill-top"><span>✓</span> Atendimento inteligente</div><div className="solution-card glass-card"><div className="card-top"><div><span className="mini-label">LESystems / Ecossistema</span><h2>Da ideia à evolução.</h2></div><span className="live-dot">● online</span></div><div className="solution-map"><div className="map-core"><span className="core-shine" aria-hidden="true" /><strong>LE</strong><small>estratégia digital</small></div>{services.map((service, index) => <Link key={service.slug} href={`/servicos/${service.slug}`} className={`map-node node-${index + 1}`}><span>{service.number}</span><b>{service.title.split(" ")[0]}</b></Link>)}</div><div className="card-footer"><span><i /> Soluções conectadas ao seu negócio</span><span>2026</span></div></div><div className="float-pill pill-bottom"><strong>IA + pessoas</strong><span>suporte para decidir melhor</span></div></div></div>
      <div className="container client-strip"><span>Tecnologia útil para</span><p>NEGÓCIOS LOCAIS</p><i /><p>EMPRESAS EM CRESCIMENTO</p><i /><p>PROFISSIONAIS</p></div>
    </section>

    <section className="express-home" aria-labelledby="express-title"><div className="container express-home-grid"><div><p className="eyebrow"><span /> LESystems Express</p><h2 id="express-title">Conte o que sua empresa precisa. <em>Nós transformamos em solução digital.</em></h2><p>Planejamento inteligente, desenvolvimento acelerado, acompanhamento online e supervisão profissional em cada etapa.</p><Link href="/criar-projeto" className="button">Criar meu projeto <ArrowIcon diagonal /></Link></div><div className="express-flow" aria-label="Fluxo do LESystems Express"><article><span>01</span><strong>Solicite</strong><small>Briefing guiado</small></article><article><span>02</span><strong>Acompanhe</strong><small>Produção e revisão</small></article><article><span>03</span><strong>Teste</strong><small>Preview validado</small></article><article><span>04</span><strong>Aprove</strong><small>Pagamento só depois</small></article></div></div></section>

    <section className="section services-section compact-section"><div className="container"><div className="section-heading"><div><p className="eyebrow"><span /> Soluções essenciais</p><h2>O necessário para sua empresa <em>avançar.</em></h2></div><p>Do primeiro site à automação da operação, criamos tecnologia clara, útil e preparada para evoluir.</p></div><div className="services-grid compact-services">{services.slice(0, 4).map((service) => <article className="service-card" key={service.slug}><div className="service-number">{service.number}</div><h3>{service.title}</h3><p>{service.short}</p><Link href={`/servicos/${service.slug}`}>Conhecer solução <ArrowIcon /></Link></article>)}</div><div className="section-action"><Link href="/servicos" className="button">Ver todas as soluções <ArrowIcon /></Link></div></div></section>

    <section className="news-home compact-news" aria-labelledby="news-home-title"><div className="container"><div className="news-home-heading"><div><p className="eyebrow"><span /> Radar de tecnologia</p><h2 id="news-home-title">Notícias que ajudam a <em>entender o futuro.</em></h2><p>Uma seleção atualizada sobre inteligência artificial, sistemas, inovação e segurança digital.</p></div><Link href="/noticias" className="button">Ver todas as notícias <ArrowIcon /></Link></div><div className="news-timeline">{timelineNews.map((item, index) => <a href={item.link} target="_blank" rel="noreferrer" className={index === 0 ? "is-latest" : ""} key={`${item.link}-${index}`}><span className="timeline-dot" aria-hidden="true" /><div className="timeline-cover" style={item.image ? { backgroundImage: `linear-gradient(180deg,transparent 28%,rgba(3,25,41,.72)),url(${JSON.stringify(item.image).slice(1,-1)})` } : undefined}><span>{item.source}</span></div><div className="timeline-content"><div className="timeline-meta"><span>{index === 0 ? "Mais recente" : item.category}</span><time>{formatNewsDate(item.date)}</time></div><h3>{item.title}</h3><p className="timeline-summary">{item.summary || "Confira os detalhes e a análise completa na publicação original."}</p><b>Ler matéria <ArrowIcon diagonal /></b></div></a>)}</div></div></section>

    <section className="section home-social-section"><div className="container"><div className="section-heading"><div><p className="eyebrow"><span /> Conteúdo LESystems</p><h2>Informação útil, <em>sem sair do site.</em></h2></div><p>Veja aqui as publicações preparadas para a comunidade da LESystems.</p></div><div className="home-social-grid">{socialPosts.map((post) => <article key={post.image}><div className="home-social-image"><Image src={post.image} alt={post.title} fill sizes="(max-width: 680px) 88vw, (max-width: 980px) 44vw, 25vw" /></div><div><span>LESystems • Facebook</span><h3>{post.title}</h3><p>{post.text}</p></div></article>)}</div></div></section>

    <section className="section quick-actions compact-contact"><div className="container contact-card light-card"><div><p className="eyebrow"><span /> Próximo passo</p><h2>Vamos transformar sua ideia em uma <em>solução real?</em></h2><p>Conte o que sua empresa precisa. A LESystems organiza o caminho e retorna com uma orientação clara.</p></div><div className="compact-contact-actions"><Link href="/contato" className="button">Solicitar uma avaliação <ArrowIcon diagonal /></Link><a href={whatsappLink("Olá, conheci o site da LESystems e gostaria de conversar sobre um projeto.")} target="_blank" rel="noreferrer" className="text-link">Conversar no WhatsApp <ArrowIcon diagonal /></a></div></div></section>
    <SiteFooter />
  </main>;
}
