import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import SiteHeader from "../../components/SiteHeader";
import SiteFooter from "../../components/SiteFooter";
import { services, whatsappLink } from "../../data";
export function generateStaticParams() { return services.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const service = services.find((item) => item.slug === slug); return service ? { title: service.title, description: service.short } : {}; }
export default async function ServicePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const service = services.find((item) => item.slug === slug); if (!service) notFound(); return <main className="site-shell"><SiteHeader /><section className="inner-hero"><div className="mesh-bg" /><div className="container inner-hero-grid"><div><p className="eyebrow"><span /> Solução {service.number}</p><h1>{service.title}</h1><p>{service.short}</p><div className="hero-actions"><Link href={`/contato?interesse=${service.slug}`} className="button">Solicitar avaliação <span>↗</span></Link><a className="text-link" href={whatsappLink(`Olá, gostaria de saber mais sobre ${service.title}.`)} target="_blank" rel="noreferrer">Conversar no WhatsApp <span>↗</span></a></div></div><aside className="service-summary"><span>Resultado esperado</span><strong>{service.outcome}</strong><div className="tag-row">{service.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></aside></div></section><section className="section detail-section"><div className="container detail-grid"><div><p className="eyebrow"><span /> O que está incluído</p><h2>Uma solução pensada <em>de ponta a ponta.</em></h2><p>{service.idealFor}</p></div><ol>{service.includes.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item}</strong></li>)}</ol></div></section><section className="section faq-section"><div className="container"><div className="section-heading compact"><div><p className="eyebrow"><span /> Perguntas frequentes</p><h2>Antes de começar.</h2></div></div><div className="faq-list"><details><summary>Quanto tempo leva?</summary><p>O prazo depende do escopo. Após a conversa inicial, organizamos etapas e apresentamos uma previsão clara.</p></details><details><summary>É possível começar pequeno?</summary><p>Sim. Priorizamos uma primeira versão útil e planejamos evoluções conforme os resultados.</p></details><details><summary>Há suporte após a entrega?</summary><p>Sim. O acompanhamento pode incluir manutenção, melhorias e orientação de uso.</p></details></div></div></section><section className="section page-cta"><div className="container contact-card light-card"><div><p className="eyebrow"><span /> Vamos conversar?</p><h2>Descubra como essa solução se adapta à <em>sua empresa.</em></h2><Link href={`/contato?interesse=${service.slug}`} className="button">Quero uma avaliação <span>↗</span></Link></div></div></section><SiteFooter /></main>; }
